apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
  labels:
    name: web-app
spec:
  replicas: 3
  selector:
    matchLabels:
      name: web-app
  template:
    metadata:
      labels:
        name: web-app
    spec:
      containers:
      - name: nginx
        image: nginx:1.23.1
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: web-app-svc
  labels:
    name: web-app
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 30080
      name: http
  selector:
    name: web-app
